# Credit Card Fraud Dataset

Link: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

pd.set_option('display.max_columns', None)

In [11]:
data_path = "../data/raw/cc_fraud/creditcard.csv"

data_df = pd.read_csv(data_path)

# split data
X = data_df.iloc[:, :-1]
y = data_df["Class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

# combine X and y again
X_train["Class"] = y_train
X_test["Class"] = y_test

train_df = X_train
test_df = X_test

In [12]:
train_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
264756,161582.0,0.223338,0.836984,-0.293565,-0.574139,0.975166,-0.726257,1.093240,-0.232010,0.289940,-0.598072,-0.795607,-0.874485,-1.284477,-0.969225,-0.019801,0.260322,0.378854,-0.163744,-0.277002,0.016099,-0.400882,-0.895258,0.087284,0.464297,-0.498658,0.095014,0.051706,-0.141865,8.95,0
113101,72933.0,1.090955,-0.210251,1.253101,0.694037,-0.782445,0.504839,-0.748042,0.312160,0.548710,-0.139511,1.319916,1.631738,0.724192,-0.337375,-0.335033,0.030415,-0.191672,-0.285079,-0.114965,-0.066194,-0.001896,0.220170,0.036146,0.075343,0.177016,0.326477,0.034278,0.015730,11.50,0
27958,34784.0,1.061632,-0.004476,0.472069,1.423305,-0.511754,-0.456862,0.043257,0.021658,0.162346,0.095316,0.959719,0.688388,-1.192068,0.449531,-0.950168,-0.242976,-0.134083,0.026837,0.194892,-0.123764,-0.047692,-0.122958,-0.107882,0.519495,0.628812,-0.373630,0.004993,0.017077,53.99,0
144697,86336.0,1.335053,0.331464,-2.057763,-0.346175,2.583234,2.854102,-0.187547,0.685154,-0.286614,-0.535903,0.332848,-0.268319,-0.127614,-0.868300,1.128539,0.786506,0.316435,0.587856,0.049350,0.045217,-0.191820,-0.650118,-0.114069,0.915936,0.730073,0.383879,-0.031902,0.029849,0.76,0
40083,40085.0,1.074308,-0.659522,0.441099,0.071028,-0.119225,1.860799,-1.003709,0.662286,-0.968471,0.787471,1.593395,0.508417,-0.322115,0.453623,1.497914,-2.148789,0.571464,0.265914,-2.459219,-0.640590,-0.034862,0.466726,0.014590,-1.377445,0.185775,-0.105284,0.121083,0.006965,29.85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97442,66223.0,-2.530636,-0.254185,1.792793,-1.192904,-1.413268,0.110981,0.768694,0.370341,0.697232,-1.562900,-0.690563,0.492041,-0.336478,-0.540596,-1.126777,0.287829,0.036025,-1.184863,-1.460069,-0.784623,-0.223404,-0.254175,0.226966,0.470334,0.270716,0.700956,-0.372193,0.032145,234.98,0
47534,43249.0,-0.811682,1.482854,0.921971,0.558934,-0.164315,-0.409506,0.183152,0.443286,-0.669139,-0.419392,-0.061597,0.151804,0.330906,-0.044646,1.616319,-0.205154,0.795626,-0.431000,0.533665,0.086535,-0.133560,-0.398416,0.092399,0.034869,-0.602976,0.202086,0.125966,0.147135,1.78,0
70629,53950.0,1.018412,1.036663,-1.689814,1.315476,1.698436,0.528807,0.331715,0.364539,-0.711798,-1.570288,3.463018,0.538411,-0.378095,-3.045495,1.468911,-0.029742,3.664588,-0.105190,-2.097944,-0.167555,-0.040238,0.096172,-0.092549,-1.345664,0.510305,-0.182674,0.107058,0.071818,0.89,0
187914,127743.0,-0.100312,0.110741,-0.467747,-0.881543,0.361230,-0.224916,1.615663,-0.116543,-0.293459,-0.769205,0.768854,0.645365,-0.449838,0.560792,-0.918920,-0.246575,-0.532466,-0.042533,0.224350,0.223736,0.087452,-0.062675,0.417744,0.678229,-0.149996,-0.207023,-0.082493,-0.000378,192.05,0
161977,114710.0,0.267682,1.679876,-4.301024,0.232818,4.346518,2.520141,1.351054,0.508759,-0.828988,-0.422446,0.517140,-0.729204,-0.610565,-1.884023,0.331808,-0.464756,2.134739,0.981472,-0.082436,0.214863,0.310681,1.276021,-0.094954,0.507997,-1.021103,-0.334290,0.788460,0.513134,30.00,0

In [13]:
test_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
234303,147915.0,-1.296864,0.744086,-0.170978,-0.674836,0.850943,-0.743948,0.514005,0.388031,-0.276231,-1.669706,0.646071,0.739571,-0.079395,-1.082321,-1.177733,0.306222,0.852034,0.709077,0.361339,-0.095864,-0.065564,-0.331204,-0.261974,-0.499306,0.088661,-0.097713,-0.159198,0.073315,30.58,0
52835,45671.0,1.217214,0.216668,0.489681,0.569450,-0.276144,-0.518583,-0.002068,-0.078610,0.010508,-0.115797,0.040933,0.562792,0.498113,0.227297,1.261424,0.000518,-0.155866,-1.016510,-0.479053,-0.112053,-0.227416,-0.613206,0.163686,0.074399,0.151364,0.123554,-0.011244,0.016053,1.79,0
168747,119364.0,-0.666579,1.511130,-0.468882,1.005551,0.514278,-0.759485,1.237812,0.048001,-0.819839,-0.151873,-1.214807,0.236156,0.212367,0.689065,-0.374800,-1.081120,0.302697,-0.358992,0.772985,-0.052480,0.165255,0.665240,-0.262915,-0.050726,0.055983,-0.382129,0.222215,0.137525,53.52,0
42002,40914.0,1.003685,-0.013222,0.461557,1.527630,-0.378175,-0.341212,0.168569,-0.053336,0.263340,-0.157861,-0.247791,0.628813,-0.196491,0.105686,-0.106458,-0.807684,0.385299,-1.067202,-0.513132,-0.056525,-0.037320,-0.035893,-0.084476,0.424085,0.592795,-0.340558,0.026656,0.031749,79.90,0
197038,131819.0,-0.515740,0.847521,0.556507,0.862111,0.502120,1.157405,-0.012968,0.802142,-0.167198,-0.535784,-0.589402,0.776983,-0.246098,0.221943,-1.590999,-0.365910,-0.051002,0.184139,1.742484,-0.087109,-0.356694,-0.997582,0.153161,-0.191265,-0.714701,-1.006413,0.131262,0.124336,19.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9179,13126.0,-2.880042,5.225442,-11.063330,6.689951,-5.759924,-2.244031,-11.199975,4.014722,-3.429304,-11.561950,10.446847,-15.479052,0.734442,-13.883779,0.821440,-11.911483,-18.103004,-6.837835,3.126929,1.191444,2.002883,0.351102,0.795255,-0.778379,-1.646815,0.487539,1.427713,0.583172,1.00,1
144661,86305.0,1.145930,0.131902,0.582682,0.509226,-0.344547,-0.312745,-0.106618,0.066582,-0.229426,0.056108,1.882426,1.197517,0.151211,0.483061,0.572038,0.149368,-0.319564,-0.557932,-0.266816,-0.107494,-0.160625,-0.485816,0.172732,0.218591,0.083800,0.093498,-0.017647,0.008699,8.99,0
54375,46420.0,1.025904,-0.021895,0.194809,1.076006,-0.376752,-0.675734,0.208182,-0.052047,-0.164509,0.166866,1.161230,0.316740,-1.205253,0.868427,0.353612,0.328161,-0.604422,0.335865,-0.022113,-0.022646,-0.025944,-0.355003,-0.083930,0.277439,0.463851,-0.505239,-0.016083,0.025629,94.63,0
125653,77748.0,-0.686503,0.611388,2.152637,-0.855286,-0.214350,-0.196052,0.274253,0.257151,-0.497546,-0.628267,1.568534,0.177481,-1.063941,0.463231,0.748368,0.157608,-0.140526,-0.137583,0.142111,-0.048749,0.002759,-0.096450,-0.157758,0.246766,-0.137733,0.940227,-0.024715,0.044379,1.23,0
86140,61098.0,-1.246566,0.534415,-0.295123,-2.088458,2.409146,2.978434,0.172959,1.249486,-0.993775,-1.126532,-0.262856,-0.083526,-0.098514,0.723218,0.589848,0.852040,-0.791610,-0.401978,0.159548,0.148362,-0.428931,-1.888895,0.115688,0.975968,0.160311,0.446072,-0.211777,-0.059850,58.96,0

In [14]:
sum_rows = train_df.shape[0] + test_df.shape[0]
train_min_num = len(train_df[train_df["Class"] == 1])
train_maj_num = len(train_df[train_df["Class"] == 0]) 


print("shape train:", train_df.shape)
print("shape test:", test_df.shape)
print("Sum rows:", sum_rows)
print()
print("Class Imbalance train:", train_min_num * 100 / train_df.shape[0])
print("Value counts label train:")
print(train_df["Class"].value_counts())
print()
print("Value counts label test:")
print(test_df["Class"].value_counts())

shape train: (227845, 31)
shape test: (56962, 31)
Sum rows: 284807

Class Imbalance train: 0.17292457591783889
Value counts label train:
Class
0    227451
1       394
Name: count, dtype: int64

Value counts label test:
Class
0    56864
1       98
Name: count, dtype: int64

### How many rows do I need to generate
(1) Input into conditional generator is 50/50   
(2) no conditional generator -> only neet to generated the difference

In [16]:
# for 1
min_amount = 394 
# times 2 since majoity class get downsampled to 7841
input_gen = min_amount * 2
reach_50 = 227451 - min_amount
to_gen = reach_50 * 2
print(to_gen)
# we expect a 50/50 distribution since train data is 50/50 so I need to divide by 2 and add the min amount and now we have the same amount of min data compared to majoirity data
print(to_gen / 2 + min_amount == 227451.0)

454114
True

In [17]:
# for 2
print(227451 - 394)

227057