In [9]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [6]:
path_real = "../data/processed/cancer_tabsyn.csv" 
path_syn = "../sdg-models/tabsyn/synthetic/cancer/tabsyn.csv"

In [7]:
df_real = pd.read_csv(path_real)
df_syn = pd.read_csv(path_syn)

In [10]:
df_real

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,dummy_cat
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,dummy
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,dummy
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,dummy
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,dummy
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,dummy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,1.1760,1.2560,7.673,158.70,0.010300,0.02891,0.05198,0.02454,0.01114,0.004239,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,dummy
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,0.7655,2.4630,5.203,99.04,0.005769,0.02423,0.03950,0.01678,0.01898,0.002498,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,dummy
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,0.4564,1.0750,3.425,48.55,0.005903,0.03731,0.04730,0.01557,0.01318,0.003892,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,dummy
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,0.7260,1.5950,5.772,86.22,0.006522,0.06158,0.07117,0.01664,0.02324,0.006185,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,dummy
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,0.3857,1.4280,2.548,19.15,0.007189,0.00466,0.00000,0.00000,0.02676,0.002783,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,dummy

In [11]:
df_syn

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,dummy_cat
0,B,14.200760,19.909143,83.99189,646.22610,0.092677,0.112942,0.058488,0.032129,0.171512,0.059990,0.305162,1.076012,1.906512,36.556522,0.006344,0.018996,0.023630,0.011359,0.020158,0.003999,16.250792,26.990290,89.034020,722.68190,0.132198,0.199831,0.287252,0.161696,0.275998,0.076379,dummy
1,M,12.445618,18.804281,84.75854,582.77700,0.100039,0.097650,0.075868,0.038977,0.177147,0.059827,0.333268,1.013206,1.883602,38.242210,0.006346,0.020171,0.023898,0.011382,0.014876,0.003470,15.348647,25.524052,108.290146,779.49610,0.125005,0.211065,0.348579,0.141902,0.256536,0.080565,dummy
2,B,13.146510,20.718163,82.61106,617.03090,0.095301,0.091384,0.060125,0.032108,0.180409,0.063794,0.284185,1.177104,1.685809,30.581755,0.006229,0.015922,0.024449,0.011383,0.018269,0.003501,20.621206,25.724438,93.644450,717.25890,0.129347,0.217884,0.303561,0.113749,0.286193,0.069844,dummy
3,M,13.498883,19.824331,81.37600,635.79156,0.096682,0.109853,0.051522,0.049296,0.172450,0.063422,0.326716,0.993991,2.138373,26.228422,0.006394,0.026232,0.027837,0.010765,0.026266,0.003433,17.171988,26.461460,82.225040,710.87897,0.128286,0.190831,0.345731,0.108967,0.254832,0.077293,dummy
4,B,14.740349,18.735823,85.02617,637.26190,0.087876,0.105705,0.070957,0.036944,0.171972,0.061503,0.295477,1.180932,2.215749,40.554210,0.006475,0.017067,0.021882,0.010824,0.019239,0.003557,14.366638,26.402824,102.390236,591.15480,0.132611,0.205988,0.161930,0.123877,0.291562,0.079820,dummy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,M,13.224908,19.373600,86.92173,688.88226,0.100606,0.093289,0.064544,0.028941,0.168498,0.063071,0.337758,1.167830,2.044648,31.114702,0.006017,0.018884,0.027726,0.011376,0.021021,0.003198,19.502420,26.901327,96.572650,632.73900,0.129674,0.175796,0.292251,0.130888,0.278490,0.075911,dummy
508,M,12.968764,18.828340,88.56602,563.70400,0.097344,0.103053,0.061766,0.034857,0.172557,0.063163,0.399417,1.041226,2.400650,41.986702,0.006615,0.018118,0.022853,0.011062,0.024598,0.003511,15.821714,25.541903,101.790900,642.91144,0.116925,0.182823,0.204051,0.113452,0.279649,0.078532,dummy
509,B,13.811143,18.347122,85.05302,557.96136,0.098152,0.108739,0.055969,0.044238,0.180998,0.062327,0.237963,1.215022,2.081263,26.512955,0.006364,0.015042,0.025289,0.013351,0.018259,0.003420,18.169987,25.638878,82.943825,689.12665,0.130924,0.181307,0.360894,0.137727,0.272149,0.076655,dummy
510,M,12.754508,18.415466,86.76898,604.81720,0.098455,0.117942,0.088871,0.036064,0.181439,0.059803,0.330533,1.316202,2.322322,40.180084,0.006584,0.024088,0.028968,0.010635,0.015838,0.003375,15.329608,27.814924,93.949210,705.00490,0.132536,0.227621,0.251034,0.151222,0.274757,0.081036,dummy
511,B,13.233110,21.285263,82.40703,720.88680,0.100287,0.078219,0.089553,0.032307,0.190347,0.062506,0.308028,1.159444,2.011226,27.901570,0.006563,0.012798,0.025875,0.011141,0.017153,0.002778,13.879393,25.549990,100.146520,706.06140,0.131408,0.180547,0.340843,0.088442,0.246929,0.080712,dummy

In [13]:
df_real["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [14]:
df_syn["diagnosis"].value_counts()

diagnosis
B    375
M    137
Name: count, dtype: int64

In [15]:
from sdv.metadata import Metadata

In [17]:
metadata = Metadata.detect_from_dataframe(
    data = df_syn,
    table_name= "cancer-tabsyn" 
)

In [18]:
from sdv.evaluation.single_table import run_diagnostic, evaluate_quality

In [19]:
diagnostic = run_diagnostic(
    real_data=df_real,
    synthetic_data=df_syn,
    metadata=metadata
)#

Generating report ...

(1/2) Evaluating Data Validity: |██████████| 32/32 [00:00<00:00, 1624.20it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<00:00, 412.87it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

In [20]:
quality_report = evaluate_quality(
    real_data=df_real,
    synthetic_data=df_syn,
    metadata=metadata)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 32/32 [00:00<00:00, 517.73it/s]|
Column Shapes Score: 66.31%

(2/2) Evaluating Column Pair Trends: |██████████| 496/496 [00:01<00:00, 425.31it/s]|
Column Pair Trends Score: 75.91%

Overall Score (Average): 71.11%