In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
path_real = "../sdg-models/tabsyn/synthetic/adult/real.csv" 
path_syn = "../sdg-models/tabsyn/synthetic/adult/tabsyn.csv"

In [3]:
df_real = pd.read_csv(path_real)
df_syn = pd.read_csv(path_syn)

In [4]:
df_real

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,35.0,Private,143058.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,<=50K
1,60.0,Private,325971.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,7688.0,0.0,40.0,United-States,>50K
2,47.0,Private,183522.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Wife,Black,Female,0.0,0.0,40.0,United-States,>50K
3,31.0,State-gov,161631.0,Some-college,10.0,Divorced,Adm-clerical,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
4,41.0,Private,49797.0,Some-college,10.0,Separated,Exec-managerial,Not-in-family,Black,Female,0.0,0.0,40.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15677,30.0,Private,231826.0,Some-college,10.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
15678,32.0,Private,37070.0,Assoc-voc,11.0,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,45.0,United-States,<=50K
15679,48.0,Self-emp-inc,382242.0,Doctorate,16.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,>50K
15680,39.0,Private,96452.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,55.0,United-States,>50K
15681,39.0,Private,58343.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,40.0,United-States,>50K

In [5]:
df_real["income"].value_counts()

income
<=50K    7841
>50K     7841
Name: count, dtype: int64

In [6]:
df_syn

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,25.000000,Private,158438.840,HS-grad,9.0,Married-civ-spouse,Other-service,Husband,Black,Male,0.0,0.0,50.0,United-States,>50K
1,61.964825,Self-emp-not-inc,55712.227,Assoc-acdm,12.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,35.0,United-States,>50K
2,56.000000,Private,177650.780,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
3,42.000000,Private,176665.560,Assoc-voc,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688.0,0.0,40.0,United-States,>50K
4,43.000000,Private,200199.620,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33753,35.000000,Local-gov,564228.900,10th,9.0,Never-married,Protective-serv,Not-in-family,White,Female,0.0,0.0,60.0,United-States,>50K
33754,23.000000,Private,162021.550,HS-grad,9.0,Never-married,Machine-op-inspct,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
33755,30.000000,Private,156882.780,HS-grad,9.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
33756,43.003124,Self-emp-not-inc,289768.940,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
33757,51.000000,Private,407067.720,Assoc-acdm,12.0,Separated,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,>50K

In [7]:
df_syn["income"].value_counts()

income
>50K     17259
<=50K    16499
Name: count, dtype: int64

In [13]:
df_real["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [14]:
df_syn["diagnosis"].value_counts()

diagnosis
B    375
M    137
Name: count, dtype: int64

In [15]:
from sdv.metadata import Metadata

In [17]:
metadata = Metadata.detect_from_dataframe(
    data = df_syn,
    table_name= "cancer-tabsyn" 
)

In [18]:
from sdv.evaluation.single_table import run_diagnostic, evaluate_quality

In [19]:
diagnostic = run_diagnostic(
    real_data=df_real,
    synthetic_data=df_syn,
    metadata=metadata
)#

Generating report ...

(1/2) Evaluating Data Validity: |██████████| 32/32 [00:00<00:00, 1624.20it/s]|
Data Validity Score: 100.0%

(2/2) Evaluating Data Structure: |██████████| 1/1 [00:00<00:00, 412.87it/s]|
Data Structure Score: 100.0%

Overall Score (Average): 100.0%

In [20]:
quality_report = evaluate_quality(
    real_data=df_real,
    synthetic_data=df_syn,
    metadata=metadata)

Generating report ...

(1/2) Evaluating Column Shapes: |██████████| 32/32 [00:00<00:00, 517.73it/s]|
Column Shapes Score: 66.31%

(2/2) Evaluating Column Pair Trends: |██████████| 496/496 [00:01<00:00, 425.31it/s]|
Column Pair Trends Score: 75.91%

Overall Score (Average): 71.11%