In [31]:
import pandas as pd
import numpy as np
import json 

from dython.nominal import compute_associations
from scipy.spatial import distance
from scipy.stats import wasserstein_distance
from sklearn.preprocessing import MinMaxScaler

In [52]:
real_path = "../sdg-models/tabsyn/synthetic/adult/real.csv"
syn_path = "../sdg-models/tabsyn/synthetic/adult/tabsyn.csv"

df_real = pd.read_csv(real_path)
df_syn = pd.read_csv(syn_path)

# load info json
with open("../sdg-models/tabsyn/data/info/adult.json", "r") as f:
        info = json.load(f)

In [3]:
df_real

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,35.0,Private,143058.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,60.0,United-States,<=50K
1,60.0,Private,325971.0,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,7688.0,0.0,40.0,United-States,>50K
2,47.0,Private,183522.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Wife,Black,Female,0.0,0.0,40.0,United-States,>50K
3,31.0,State-gov,161631.0,Some-college,10.0,Divorced,Adm-clerical,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
4,41.0,Private,49797.0,Some-college,10.0,Separated,Exec-managerial,Not-in-family,Black,Female,0.0,0.0,40.0,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15677,30.0,Private,231826.0,Some-college,10.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,40.0,United-States,>50K
15678,32.0,Private,37070.0,Assoc-voc,11.0,Never-married,Craft-repair,Not-in-family,White,Male,0.0,0.0,45.0,United-States,<=50K
15679,48.0,Self-emp-inc,382242.0,Doctorate,16.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,>50K
15680,39.0,Private,96452.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,55.0,United-States,>50K
15681,39.0,Private,58343.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,40.0,United-States,>50K

In [7]:
df_syn

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,25.000000,Private,158438.840,HS-grad,9.0,Married-civ-spouse,Other-service,Husband,Black,Male,0.0,0.0,50.0,United-States,>50K
1,61.964825,Self-emp-not-inc,55712.227,Assoc-acdm,12.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,35.0,United-States,>50K
2,56.000000,Private,177650.780,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K
3,42.000000,Private,176665.560,Assoc-voc,13.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,7688.0,0.0,40.0,United-States,>50K
4,43.000000,Private,200199.620,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,50.0,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33753,35.000000,Local-gov,564228.900,10th,9.0,Never-married,Protective-serv,Not-in-family,White,Female,0.0,0.0,60.0,United-States,>50K
33754,23.000000,Private,162021.550,HS-grad,9.0,Never-married,Machine-op-inspct,Own-child,White,Male,0.0,0.0,40.0,United-States,<=50K
33755,30.000000,Private,156882.780,HS-grad,9.0,Never-married,Machine-op-inspct,Unmarried,White,Female,0.0,0.0,40.0,United-States,<=50K
33756,43.003124,Self-emp-not-inc,289768.940,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,0.0,40.0,United-States,<=50K
33757,51.000000,Private,407067.720,Assoc-acdm,12.0,Separated,Exec-managerial,Wife,White,Female,0.0,0.0,40.0,United-States,>50K

In [8]:
df_real["income"].value_counts()

income
<=50K    7841
>50K     7841
Name: count, dtype: int64

In [9]:
df_syn["income"].value_counts()

income
>50K     17259
<=50K    16499
Name: count, dtype: int64

In [70]:
# NaNs are read as float this breaks the code will transfrom to 'missing' for categoricalo columns
cat_cols= adult_categorical = ['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country', 'income']

for col in cat_cols:
    df_real[col] = df_real[col].replace(0.0, 'missing')
    df_syn[col] = df_syn[col].replace(0.0, 'missing')

## Statistical similarity

In [72]:
# code from ctab-gan-plus repo 
really = df_real.copy()
fakey = df_syn.copy()

# create corrleation matrix
real_corr = compute_associations(df_real, nominal_columns=cat_cols)
syn_corr = compute_associations(df_syn, nominal_columns=cat_cols)

In [74]:
corr_dist = np.linalg.norm(real_corr - syn_corr)

In [75]:
Stat_dict = {}
cat_stat = []
num_stat = []

for column in df_real.columns:
        
    if column in cat_cols:
        #print(column)

        real_pdf=(really[column].value_counts()/really[column].value_counts().sum())
        fake_pdf=(fakey[column].value_counts()/fakey[column].value_counts().sum())
        categories = (fakey[column].value_counts()/fakey[column].value_counts().sum()).keys().tolist()
        sorted_categories = sorted(categories)
        
        real_pdf_values = [] 
        fake_pdf_values = []

        for i in sorted_categories:
            real_pdf_values.append(real_pdf[i])
            fake_pdf_values.append(fake_pdf[i])

        if len(real_pdf)!=len(fake_pdf):
            zero_cats = set(really[column].value_counts().keys())-set(fakey[column].value_counts().keys())
            for z in zero_cats:
                real_pdf_values.append(real_pdf[z])
                fake_pdf_values.append(0)
        Stat_dict[column]=(distance.jensenshannon(real_pdf_values,fake_pdf_values, 2.0))
        cat_stat.append(Stat_dict[column])    
        print("column: ", column, "JSD: ", Stat_dict[column])  
    else:
        scaler = MinMaxScaler()
        scaler.fit(df_real[column].values.reshape(-1,1))
        l1 = scaler.transform(df_real[column].values.reshape(-1,1)).flatten()
        l2 = scaler.transform(df_syn[column].values.reshape(-1,1)).flatten()
        Stat_dict[column]= (wasserstein_distance(l1,l2))
        print("column: ", column, "WD: ", Stat_dict[column])
        num_stat.append(Stat_dict[column])

column:  age WD:  0.0034392463923820717
workclass
column:  workclass JSD:  0.03122529547046864
column:  fnlwgt WD:  0.0008187794132309643
education
column:  education JSD:  0.03820892557659078
column:  education.num WD:  0.004402104551438246
marital.status
column:  marital.status JSD:  0.022092910072399337
occupation
column:  occupation JSD:  0.04724614053342541
relationship
column:  relationship JSD:  0.009482097279248458
race
column:  race JSD:  0.02237077981301528
sex
column:  sex JSD:  0.0064724424880911735
column:  capital.gain WD:  0.004125651937904421
column:  capital.loss WD:  0.00208954179202446
column:  hours.per.week WD:  0.005029731035585274
native.country
column:  native.country JSD:  0.05790220350823997
income
column:  income JSD:  0.009561174950196984

In [76]:
print(np.mean(num_stat),np.mean(cat_stat),corr_dist)

0.0033175091870942396 0.027173552187964006 0.411851167316875

In [77]:
stat_res_avg = []
stat_res_avg.append([np.mean(num_stat),np.mean(cat_stat),corr_dist])
stat_columns = ["Average WD (Continuous Columns","Average JSD (Categorical Columns)","Correlation Distance"]
stat_results = pd.DataFrame(np.array(stat_res_avg).mean(axis=0).reshape(1,3),columns=stat_columns)
stat_results

,Average WD (Continuous Columns,Average JSD (Categorical Columns),Correlation Distance
0,0.003318,0.027174,0.411851

### Interpretation

-> lower values indicates a better result

## alpha-Precision & beta-Recall

- alpha-Precision: evaluates the fidelity of synthetic data -> whether each synthetic example comes from the real-data distribution
- beta-Recall: evaluates the coverge of the synthetic data -> whether the synthetic data can cover the entire distribution of the real data (in other words: whether a reald data sample is close to the syhnthetic data)

-> higher values indicate superior performance


Code from TabSyn

In [1]:
import json
import pandas as pd
import numpy as np
from synthcity.metrics import eval_detection, eval_performance, eval_statistical
from synthcity.plugins.core.dataloader import GenericDataLoader
from sklearn.preprocessing import OneHotEncoder
import os

/Users/markusmuller/miniconda3/envs/sdg-eda-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[KeOps] Warning : omp.h header is not in the path, disabling OpenMP. To fix this, you can set the environment
                  variable OMP_PATH to the location of the header before importing keopscore or pykeops,
                  e.g. using os.environ: import os; os.environ['OMP_PATH'] = '/path/to/omp/header'
[KeOps] Warning : Cuda libraries were not detected on the system or could not be loaded ; using cpu only mode

In [2]:
real_path = "../sdg-models/tabsyn/synthetic/adult/real.csv"
syn_path = "../sdg-models/tabsyn/synthetic/adult/tabsyn.csv"

real_data = pd.read_csv(real_path)
syn_data = pd.read_csv(syn_path)

# load info json
with open("../sdg-models/tabsyn/data/info/adult.json", "r") as f:
        info = json.load(f)

In [3]:
dataname = "adult"
model = "tabsyn"

real_data.columns = range(len(real_data.columns))
syn_data.columns = range(len(syn_data.columns))

num_col_idx = info['num_col_idx']
cat_col_idx = info['cat_col_idx']
target_col_idx = info['target_col_idx']
cat_col_idx += target_col_idx
    
num_real_data = real_data[num_col_idx]
cat_real_data = real_data[cat_col_idx]

num_real_data_np = num_real_data.to_numpy()
cat_real_data_np = cat_real_data.to_numpy().astype('str')
    

num_syn_data = syn_data[num_col_idx]
cat_syn_data = syn_data[cat_col_idx]

num_syn_data_np = num_syn_data.to_numpy()

# cat_syn_data_np = np.array
cat_syn_data_np = cat_syn_data.to_numpy().astype('str')
if (dataname == 'default' or dataname == 'news') and model[:4] == 'codi':
    cat_syn_data_np = cat_syn_data.astype('int').to_numpy().astype('str')

elif model[:5] == 'great':
    if dataname == 'shoppers':
        cat_syn_data_np[:, 1] = cat_syn_data[11].astype('int').to_numpy().astype('str')
        cat_syn_data_np[:, 2] = cat_syn_data[12].astype('int').to_numpy().astype('str')
        cat_syn_data_np[:, 3] = cat_syn_data[13].astype('int').to_numpy().astype('str')
        
        max_data = cat_real_data[14].max()
    
        cat_syn_data.loc[cat_syn_data[14] > max_data, 14] = max_data
        # cat_syn_data[14] = cat_syn_data[14].apply(lambda x: threshold if x > max_data else x)
        
        cat_syn_data_np[:, 4] = cat_syn_data[14].astype('int').to_numpy().astype('str')
        cat_syn_data_np[:, 4] = cat_syn_data[14].astype('int').to_numpy().astype('str')
    
    elif dataname in ['default', 'faults', 'beijing']:

        columns = cat_real_data.columns
        for i, col in enumerate(columns):
            if (cat_real_data[col].dtype == 'int'):

                max_data = cat_real_data[col].max()
                min_data = cat_real_data[col].min()

                cat_syn_data.loc[cat_syn_data[col] > max_data, col] = max_data
                cat_syn_data.loc[cat_syn_data[col] < min_data, col] = min_data

                cat_syn_data_np[:, i] = cat_syn_data[col].astype('int').to_numpy().astype('str')
                
    else:
        cat_syn_data_np = cat_syn_data.to_numpy().astype('str')

else:
    cat_syn_data_np = cat_syn_data.to_numpy().astype('str')

encoder = OneHotEncoder()
encoder.fit(cat_real_data_np)


cat_real_data_oh = encoder.transform(cat_real_data_np).toarray()
cat_syn_data_oh = encoder.transform(cat_syn_data_np).toarray()

le_real_data = pd.DataFrame(np.concatenate((num_real_data_np, cat_real_data_oh), axis = 1)).astype(float)
le_real_num = pd.DataFrame(num_real_data_np).astype(float)
le_real_cat = pd.DataFrame(cat_real_data_oh).astype(float)


le_syn_data = pd.DataFrame(np.concatenate((num_syn_data_np, cat_syn_data_oh), axis = 1)).astype(float)
le_syn_num = pd.DataFrame(num_syn_data_np).astype(float)
le_syn_cat = pd.DataFrame(cat_syn_data_oh).astype(float)

np.set_printoptions(precision=4)

result = []

print('=========== All Features ===========')
print('Data shape: ', le_syn_data.shape)

X_syn_loader = GenericDataLoader(le_syn_data)
X_real_loader = GenericDataLoader(le_real_data)

quality_evaluator = eval_statistical.AlphaPrecision()
qual_res = quality_evaluator.evaluate(X_real_loader, X_syn_loader)
qual_res = {
    k: v for (k, v) in qual_res.items() if "naive" in k
}  # use the naive implementation of AlphaPrecision
qual_score = np.mean(list(qual_res.values()))

print('alpha precision: {:.6f}, beta recall: {:.6f}'.format(qual_res['delta_precision_alpha_naive'], qual_res['delta_coverage_beta_naive'] ))

Alpha_Precision_all = qual_res['delta_precision_alpha_naive']
Beta_Recall_all = qual_res['delta_coverage_beta_naive']

: