In [1]:
import pandas as pd

In [8]:
path_syn = "../sdg-models/tabsyn/synthetic/adult/tabsyn.csv"

In [9]:
df_syn = pd.read_csv(path_syn)

In [10]:
df_syn

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,38.0,NaN,217196.11,Bachelors,10.000000,Never-married,Exec-managerial,Unmarried,White,Female,0.0,0.0,40.000000,Iran,<=50K
1,19.0,Federal-gov,136005.45,12th,10.000000,Never-married,Transport-moving,Unmarried,Other,Male,0.0,0.0,40.000000,Iran,<=50K
2,47.0,Without-pay,193150.05,10th,9.000000,Married-civ-spouse,Exec-managerial,Unmarried,White,Male,0.0,0.0,40.000000,Iran,<=50K
3,30.0,Private,217512.55,1st-4th,9.000000,Married-civ-spouse,Exec-managerial,Unmarried,Other,Male,0.0,0.0,45.355198,Iran,<=50K
4,31.0,Federal-gov,79372.29,Doctorate,10.000000,Never-married,Transport-moving,Unmarried,White,Female,0.0,0.0,40.000000,Iran,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,48.0,Never-worked,233031.48,12th,10.000000,Married-civ-spouse,Transport-moving,Unmarried,White,Male,0.0,0.0,40.000000,Iran,<=50K
32557,47.0,Federal-gov,193957.23,Doctorate,10.000000,Married-civ-spouse,Transport-moving,Unmarried,White,Male,0.0,0.0,50.000000,Iran,<=50K
32558,24.0,Federal-gov,160947.30,Bachelors,10.000000,Never-married,Exec-managerial,Unmarried,Asian-Pac-Islander,Male,0.0,0.0,40.000000,Iran,<=50K
32559,38.0,Federal-gov,203776.50,12th,9.948622,Married-civ-spouse,Other-service,Unmarried,White,Male,0.0,0.0,40.000000,Iran,<=50K
32560,34.0,Federal-gov,177547.95,Bachelors,9.000000,Married-civ-spouse,Exec-managerial,Unmarried,Other,Female,0.0,0.0,35.000000,Iran,<=50K

In [12]:
df_syn["income"].value_counts()

income
<=50K    32364
>50K       197
Name: count, dtype: int64

In [13]:
df_syn["native.country"].value_counts()

native.country
Iran             30396
United-States     2087
Cambodia            74
Yugoslavia           4
Name: count, dtype: int64

In [14]:
path_syn = "../sdg-models/tabsyn/synthetic/adult/tabsyn_new.csv"

In [15]:
df_syn = pd.read_csv(path_syn)

In [16]:
df_syn

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,25.483408,Private,157694.11,7th-8th,11.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,50.0000,India,<=50K
1,36.000000,Private,230668.60,Masters,12.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,55.8321,Peru,<=50K
2,37.000000,Self-emp-not-inc,225013.77,Preschool,9.0,Married-civ-spouse,Craft-repair,Husband,White,Female,0.0,0.0,40.0000,India,<=50K
3,38.000000,Private,155860.75,Prof-school,10.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,0.0,40.0000,Trinadad&Tobago,<=50K
4,26.000000,Private,105220.44,11th,10.0,Married-civ-spouse,Transport-moving,Husband,White,Female,0.0,0.0,40.0000,Peru,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,24.000000,Private,111535.00,1st-4th,10.0,Married-civ-spouse,Craft-repair,Husband,Other,Female,0.0,0.0,40.0000,Peru,<=50K
32557,31.000000,Private,222109.33,Prof-school,11.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0000,India,<=50K
32558,36.000000,Private,106611.48,11th,12.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,0.0,40.0000,Trinadad&Tobago,<=50K
32559,35.000000,Private,223481.22,Prof-school,10.0,Never-married,Adm-clerical,Husband,White,Female,0.0,0.0,40.0000,Portugal,<=50K
32560,30.000000,Private,98018.41,1st-4th,9.0,Married-civ-spouse,Transport-moving,Husband,White,Male,0.0,0.0,38.0000,Peru,<=50K

In [17]:
df_syn["income"].value_counts()

income
<=50K    31758
>50K       803
Name: count, dtype: int64