In [11]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import json

In [7]:
DATASET = "adult"
SDG = "ctgan"

In [8]:
data_path_train = f"../data/processed/{DATASET}/train.csv"
syn_path_train = f"../data/synthetic/{DATASET}/{SDG}.csv"
data_path_test = f"../data/processed/{DATASET}/test.csv"

In [9]:
# read data 
df_train_ci = pd.read_csv(data_path_train)
df_train_syn = pd.read_csv(syn_path_train)
df_test = pd.read_csv(data_path_test)

In [12]:
info_path = f"../data/raw/{DATASET}/{DATASET}.json"
# load info json
with open(info_path, "r") as f:
    info = json.load(f)

In [13]:
cat_columns_idx = info["cat_col_idx"]
columns_names = info["column_names"]
cat_columns_names = [columns_names[i] for i in cat_columns_idx]

In [17]:
# Function to apply OneHotEncoding to a DataFrame
def apply_onehot_encoding(train_df, test_df, categorical_columns):
    # Create OneHotEncoder
    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

    # Apply ColumnTransformer to the categorical columns
    preprocessor = ColumnTransformer(
        transformers=[(col, encoder, [col]) for col in categorical_columns],
        remainder='passthrough'  # Keep non-categorical columns unchanged
    )
    
    # Fit the encoder on the train data and transform both train and test data
    train_encoded = preprocessor.fit_transform(train_df)
    test_encoded = preprocessor.transform(test_df)

    # Convert the encoded data back to DataFrame
    train_encoded_df = pd.DataFrame(train_encoded, columns=preprocessor.get_feature_names_out())
    test_encoded_df = pd.DataFrame(test_encoded, columns=preprocessor.get_feature_names_out())
    
    # Return the encoded DataFrames
    return train_encoded_df, test_encoded_df

In [18]:
df_train_enc, df_test_enc = apply_onehot_encoding(df_train_ci, df_test, cat_columns_names)

In [19]:
df_train_enc

,workclass__workclass_Federal-gov,workclass__workclass_Local-gov,workclass__workclass_Never-worked,workclass__workclass_Private,workclass__workclass_Self-emp-inc,workclass__workclass_Self-emp-not-inc,workclass__workclass_State-gov,workclass__workclass_Without-pay,workclass__workclass_nan,education__education_10th,...,native.country__native.country_Vietnam,native.country__native.country_Yugoslavia,native.country__native.country_nan,remainder__age,remainder__fnlwgt,remainder__education.num,remainder__capital.gain,remainder__capital.loss,remainder__hours.per.week,remainder__income
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,39.0,77516.0,13.0,2174.0,0.0,40.0,<=50K
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,50.0,83311.0,13.0,0.0,0.0,13.0,<=50K
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,38.0,215646.0,9.0,0.0,0.0,40.0,<=50K
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,53.0,234721.0,7.0,0.0,0.0,40.0,<=50K
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,28.0,338409.0,13.0,0.0,0.0,40.0,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,27.0,257302.0,12.0,0.0,0.0,38.0,<=50K
32557,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,40.0,154374.0,9.0,0.0,0.0,40.0,>50K
32558,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,58.0,151910.0,9.0,0.0,0.0,40.0,<=50K
32559,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,22.0,201490.0,9.0,0.0,0.0,20.0,<=50K
32560,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,52.0,287927.0,9.0,15024.0,0.0,40.0,>50K

In [20]:
df_test_enc

,workclass__workclass_Federal-gov,workclass__workclass_Local-gov,workclass__workclass_Never-worked,workclass__workclass_Private,workclass__workclass_Self-emp-inc,workclass__workclass_Self-emp-not-inc,workclass__workclass_State-gov,workclass__workclass_Without-pay,workclass__workclass_nan,education__education_10th,...,native.country__native.country_Vietnam,native.country__native.country_Yugoslavia,native.country__native.country_nan,remainder__age,remainder__fnlwgt,remainder__education.num,remainder__capital.gain,remainder__capital.loss,remainder__hours.per.week,remainder__income
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,226802.0,7.0,0.0,0.0,40.0,<=50K
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,38.0,89814.0,9.0,0.0,0.0,50.0,<=50K
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,28.0,336951.0,12.0,0.0,0.0,40.0,>50K
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,44.0,160323.0,10.0,7688.0,0.0,40.0,>50K
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,18.0,103497.0,10.0,0.0,0.0,30.0,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16276,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,39.0,215419.0,13.0,0.0,0.0,36.0,<=50K
16277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,64.0,321403.0,9.0,0.0,0.0,40.0,<=50K
16278,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,38.0,374983.0,13.0,0.0,0.0,50.0,<=50K
16279,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,44.0,83891.0,13.0,5455.0,0.0,40.0,<=50K
16280,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,35.0,182148.0,13.0,0.0,0.0,60.0,>50K

In [21]:
df_test_enc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16281 entries, 0 to 16280
Columns: 109 entries, workclass__workclass_Federal-gov to remainder__income
dtypes: object(109)
memory usage: 13.5+ MB

In [25]:
df_test_enc.columns.to_list()

['workclass__workclass_Federal-gov',
 'workclass__workclass_Local-gov',
 'workclass__workclass_Never-worked',
 'workclass__workclass_Private',
 'workclass__workclass_Self-emp-inc',
 'workclass__workclass_Self-emp-not-inc',
 'workclass__workclass_State-gov',
 'workclass__workclass_Without-pay',
 'workclass__workclass_nan',
 'education__education_10th',
 'education__education_11th',
 'education__education_12th',
 'education__education_1st-4th',
 'education__education_5th-6th',
 'education__education_7th-8th',
 'education__education_9th',
 'education__education_Assoc-acdm',
 'education__education_Assoc-voc',
 'education__education_Bachelors',
 'education__education_Doctorate',
 'education__education_HS-grad',
 'education__education_Masters',
 'education__education_Preschool',
 'education__education_Prof-school',
 'education__education_Some-college',
 'marital.status__marital.status_Divorced',
 'marital.status__marital.status_Married-AF-spouse',
 'marital.status__marital.status_Married-civ-spouse',
 'marital.status__marital.status_Married-spouse-absent',
 'marital.status__marital.status_Never-married',
 'marital.status__marital.status_Separated',
 'marital.status__marital.status_Widowed',
 'occupation__occupation_Adm-clerical',
 'occupation__occupation_Armed-Forces',
 'occupation__occupation_Craft-repair',
 'occupation__occupation_Exec-managerial',
 'occupation__occupation_Farming-fishing',
 'occupation__occupation_Handlers-cleaners',
 'occupation__occupation_Machine-op-inspct',
 'occupation__occupation_Other-service',
 'occupation__occupation_Priv-house-serv',
 'occupation__occupation_Prof-specialty',
 'occupation__occupation_Protective-serv',
 'occupation__occupation_Sales',
 'occupation__occupation_Tech-support',
 'occupation__occupation_Transport-moving',
 'occupation__occupation_nan',
 'relationship__relationship_Husband',
 'relationship__relationship_Not-in-family',
 'relationship__relationship_Other-relative',
 'relationship__relationship_Own-child',
 'relationship__relationship_Unmarried',
 'relationship__relationship_Wife',
 'race__race_Amer-Indian-Eskimo',
 'race__race_Asian-Pac-Islander',
 'race__race_Black',
 'race__race_Other',
 'race__race_White',
 'sex__sex_Female',
 'sex__sex_Male',
 'native.country__native.country_Cambodia',
 'native.country__native.country_Canada',
 'native.country__native.country_China',
 'native.country__native.country_Columbia',
 'native.country__native.country_Cuba',
 'native.country__native.country_Dominican-Republic',
 'native.country__native.country_Ecuador',
 'native.country__native.country_El-Salvador',
 'native.country__native.country_England',
 'native.country__native.country_France',
 'native.country__native.country_Germany',
 'native.country__native.country_Greece',
 'native.country__native.country_Guatemala',
 'native.country__native.country_Haiti',
 'native.country__native.country_Holand-Netherlands',
 'native.country__native.country_Honduras',
 'native.country__native.country_Hong',
 'native.country__native.country_Hungary',
 'native.country__native.country_India',
 'native.country__native.country_Iran',
 'native.country__native.country_Ireland',
 'native.country__native.country_Italy',
 'native.country__native.country_Jamaica',
 'native.country__native.country_Japan',
 'native.country__native.country_Laos',
 'native.country__native.country_Mexico',
 'native.country__native.country_Nicaragua',
 'native.country__native.country_Outlying-US(Guam-USVI-etc)',
 'native.country__native.country_Peru',
 'native.country__native.country_Philippines',
 'native.country__native.country_Poland',
 'native.country__native.country_Portugal',
 'native.country__native.country_Puerto-Rico',
 'native.country__native.country_Scotland',
 'native.country__native.country_South',
 'native.country__native.country_Taiwan',
 'native.country__native.country_Thailand',
 'native.country__native.country_Trinadad&Tobago',
 'native.country__native.country_United-States',
 'native.country__native.country_Vietnam',
 'native.country__native.country_Yugoslavia',
 'native.country__native.country_nan',
 'remainder__age',
 'remainder__fnlwgt',
 'remainder__education.num',
 'remainder__capital.gain',
 'remainder__capital.loss',
 'remainder__hours.per.week',
 'remainder__income']